---
- hosts: jupiter
  remote_user: ubuntu
  become: yes
  
  tasks:
        
    - name: Install pip
      become: yes
      ansible.builtin.apt:
        name: python3-pip 
        update_cache: true
    
    - name: Install Jupiter
      ansible.builtin.pip:
        name:
          - jupyterhub
    
    - name: Install soft
      ansible.builtin.apt:
        name:
          - npm
          - nodejs
    
    - name: Install hhtp-proxy
      community.general.npm:
        name: configurable-http-proxy
        global: true

    - name: Config jupyterhub
      ansible.builtin.shell:
        cmd: jupyterhub --generate-config
        
    - name: Start jupyterhub
      ansible.builtin.shell:
        cmd: jupyterhub
        