---
- hosts: amundsen
  remote_user: ubuntu
  become: yes
  
  tasks:
        
    - name: Install pip
      become: yes
      ansible.builtin.apt:
        name: python3-pip 
        update_cache: true
    
    