version: "3"


services:
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000


networks:
  default:
    name: my-local-net