version: '3.8'
services:
  app:
    
    image: 
    ports:
      -5000:5000
    volumes:
      -.:/app
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    