version: '3.8'
services:
  app:
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - postgres
    entrypoint: ["python", "main.py","runserver"]
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    volumes:
      - ./postgres-data:/var/lib/postgresgl/data
    ports:
      - 5432:5432
    