---
- name: Install nginx & postgres
  hosts: all
  become: true
  remote_user: admin-f

  tasks:
  - name: Install nginx
    apt:
      name: nginx
      
  - name: Install postgres
    apt:
      name: postgresql
      